FROM docker.io/python:3.12-slim

COPY ./requirements.txt /app/requirements.txt
COPY ./main.py /app/main.py

WORKDIR /app

RUN pip install -r requirements.txt

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

CMD ["fastapi", "run"] 
