events {
    # The events block is required but can be left empty for basic configurations.
    # It usually contains directives that affect the connection handling.
}

http {
    # The http block includes settings for handling HTTP traffic.

    include       mime.types;
    # Specifies the file that defines MIME types for various file extensions.

    default_type  application/octet-stream;
    # Sets the default MIME type for files when the type is not determined.

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    # Defines a custom log format called 'main' for access logs.

    access_log  /var/log/nginx/access.log  main;
    # Specifies the file and format for access logs.

    error_log   /var/log/nginx/error.log warn;
    # Specifies the file and log level for error logs.

    sendfile        on;
    # Enables the use of sendfile for efficient file transfer.

    keepalive_timeout  65;
    # Sets the timeout for persistent connections with the client.

    upstream api {
        server api:8000;
    }

    server {
        listen 8000;
        
        server_name localhost;

        location /test {
            proxy_pass http://api/test;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /status {
            proxy_pass http://api/status;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /authcodes {
            proxy_pass http://api/authcodes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
	location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
	}
	location /ws {
		proxy_pass http://api/ws;
            	proxy_set_header Host $host;
            	proxy_set_header X-Real-IP $remote_addr;
            	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            	proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}
    }
}
