FROM docker.io/python:3.12-slim

COPY ./transactions.csv /app/transactions.csv
COPY ./transactions_auth_codes.csv /app/transactions_auth_codes.csv
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY ./client_authcode.py /app/main.py

CMD ["/app/main.py"]
